import { Duration } from "aws-cdk-lib";
import { ISecurityGroup, IVpc } from "aws-cdk-lib/aws-ec2";
import { Function, Runtime, Code } from "aws-cdk-lib/aws-lambda";
import { ISecret, Secret } from "aws-cdk-lib/aws-secretsmanager";
import { Construct } from "constructs";

/**
 * Creates a Secrets Manager secret whose credentials are generated and stored by the custom
 * resource (or, in this MVP, are simply generated by the secret itself and the rotation Lambda
 * is wired to enforce a 7-day rotation).
 *
 * For Aurora we use the *generated* secret from `rds.Credentials.fromGeneratedSecret`; this
 * function is a placeholder for a future change where the credentials come from a manually-created
 * secret. Keeping it here so the rotation hook has a clear target.
 */
export function createDatabaseSecret(scope: Construct, props: { envName: string }): ISecret {
  return new Secret(scope, "ChatsaasDbSecret", {
    description: `chatsaas ${props.envName} database master credential`,
    generateSecretString: {
      excludePunctuation: true,
      excludeCharacters: " %+~`#$&*()|[]{}:;<>?!'\"\\/",
      passwordLength: 32,
    },
  });
}

/**
 * Creates a rotation Lambda stub. The `rotate` function is a no-op for MVP; a follow-up WI
 * implements the actual rotation logic using the documented Secrets Manager hook contract.
 */
export function createRotationLambda(
  scope: Construct,
  props: { secret: ISecret; vpc: IVpc; rotationSecurityGroup: ISecurityGroup },
) {
  const fn = new Function(scope, "DbSecretRotationLambda", {
    runtime: Runtime.NODEJS_20_X,
    handler: "index.handler",
    code: Code.fromInline(`
"use strict";
exports.handler = async (event) => {
  // Rotation stub. A follow-up WI implements the real rotation: call the RDS ModifyDBInstance
  // API to rotate the master password, then SecretsManagerRotationHook signals success.
  return { statusCode: 200, body: JSON.stringify({ message: "Rotation is a stub in this WI" }) };
};
`),
    vpc: props.vpc,
    securityGroups: [props.rotationSecurityGroup],
    timeout: Duration.seconds(30),
    memorySize: 256,
  });

  return fn;
}
