import { createServer, type Server } from 'node:https'
import type { IncomingMessage, ServerResponse } from 'node:http'
import { readFileSync } from 'node:fs'
import { exportJWK, generateKeyPair, SignJWT, type JWTPayload } from 'jose'

/**
 * Fake Cognito for the SANDBOX web e2e (apps/web/e2e/sandbox-flow):
 * a real HTTPS OAuth2 IdP on 127.0.0.1:4568 so the app's ACTUAL
 * authorization-code + PKCE flow runs end to end — no forged cookies.
 *
 * Serves the three endpoints apps/web/src/lib/oauth.ts + jwt.ts touch:
 *
 *   GET  /.well-known/jwks.json  — RS256 public key (kid sandbox-key-1),
 *                                  fetched by lib/jwt.ts (middleware).
 *   GET  /oauth2/authorize       — "auto-approve" login: 302 straight
 *                                  back to the redirect_uri with a fixed
 *                                  code and the echoed state. PKCE is NOT
 *                                  validated here; the token endpoint
 *                                  accepts any verifier (sandbox IdP).
 *   POST /oauth2/token           — exchanges ANY code for a fresh RS256
 *                                  token pair (id + access + refresh),
 *                                  1h expiry, issuer EXACTLY
 *                                  `https://127.0.0.1:4568` (no trailing
 *                                  slash — lib/jwt.ts strips trailing
 *                                  slashes from the env value, so the
 *                                  claim and the expectation must match).
 *
 * Claims mirror the sandbox API's stubbed auth (SANDBOX_USER_SUB /
 * SANDBOX_COMPANY_ID in apps/functions/.env) so the UI renders the same
 * operator/company the API assumes:
 *
 *   access: token_use='access', client_id=<client id>, sub, email,
 *           custom:company_id
 *   id:     token_use='id', aud=<client id>, sub, email,
 *           custom:company_id
 *
 * TLS uses the self-signed cert at /tmp/opencode/sandbox/ (generated by
 * the sandbox setup). Browsers opt in via Playwright's
 * ignoreHTTPSErrors; the Next dev server trusts it via NODE_EXTRA_CA_CERTS.
 */

const PORT = Number(process.env.E2E_FAKE_COGNITO_PORT ?? 4568)
const HOST = process.env.E2E_FAKE_COGNITO_HOST ?? '127.0.0.1'

/** EXACT issuer — must equal NEXT_PUBLIC_COGNITO_ISSUER_URL (sans slashes). */
const ISSUER = (process.env.E2E_FAKE_COGNITO_ISSUER ?? `https://${HOST}:${PORT}`).replace(/\/+$/, '')
const CLIENT_ID = process.env.E2E_FAKE_COGNITO_CLIENT_ID ?? 'sandbox-web-client'
const SUB = process.env.E2E_FAKE_COGNITO_SUB ?? 'sandbox-user-1'
const COMPANY_ID =
  process.env.E2E_FAKE_COGNITO_COMPANY_ID ?? 'c0ffee00-0000-4000-8000-000000000001'
const EMAIL = process.env.E2E_FAKE_COGNITO_EMAIL ?? 'sandbox@chatsaas.test'

const KID = 'sandbox-key-1'
const AUTHORIZATION_CODE = 'sandbox-code-1'
const REFRESH_TOKEN = 'sandbox-refresh-token'

const TLS_KEY_PATH =
  process.env.E2E_FAKE_COGNITO_TLS_KEY ?? '/tmp/opencode/sandbox/fake-cognito-key.pem'
const TLS_CERT_PATH =
  process.env.E2E_FAKE_COGNITO_TLS_CERT ?? '/tmp/opencode/sandbox/fake-cognito-cert.pem'

const { publicKey, privateKey } = await generateKeyPair('RS256', { extractable: true })
const publicJwk = { ...(await exportJWK(publicKey)), kid: KID, use: 'sig', alg: 'RS256' }

async function sign(payload: JWTPayload): Promise<string> {
  return new SignJWT(payload)
    .setProtectedHeader({ alg: 'RS256', kid: KID })
    .setIssuedAt()
    .setExpirationTime('1h')
    .setIssuer(ISSUER)
    .sign(privateKey)
}

async function mintTokens(): Promise<{ id_token: string; access_token: string }> {
  const id_token = await sign({
    sub: SUB,
    email: EMAIL,
    token_use: 'id',
    aud: CLIENT_ID,
    'cognito:username': SUB,
    'custom:company_id': COMPANY_ID,
  })
  const access_token = await sign({
    sub: SUB,
    email: EMAIL,
    token_use: 'access',
    client_id: CLIENT_ID,
    username: SUB,
    'custom:company_id': COMPANY_ID,
  })
  return { id_token, access_token }
}

function readBody(req: IncomingMessage): Promise<string> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = []
    req.on('data', (chunk: Buffer) => chunks.push(chunk))
    req.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')))
    req.on('error', reject)
  })
}

const server: Server = createServer(
  { key: readFileSync(TLS_KEY_PATH), cert: readFileSync(TLS_CERT_PATH) },
  async (req: IncomingMessage, res: ServerResponse) => {
    const url = new URL(req.url ?? '/', ISSUER)
    try {
      if (req.method === 'GET' && url.pathname === '/.well-known/jwks.json') {
        res.writeHead(200, { 'content-type': 'application/json' })
        res.end(JSON.stringify({ keys: [publicJwk] }))
        return
      }

      if (req.method === 'GET' && url.pathname === '/oauth2/authorize') {
        // Sandbox login is auto-approve: bounce straight back with a fixed
        // code and the caller's state (CSRF echo). PKCE is intentionally
        // not validated — the token endpoint accepts any verifier.
        const redirectUri = url.searchParams.get('redirect_uri')
        if (!redirectUri) {
          res.writeHead(400, { 'content-type': 'application/json' })
          res.end(JSON.stringify({ error: 'invalid_request', error_description: 'missing redirect_uri' }))
          return
        }
        const target = new URL(redirectUri)
        target.searchParams.set('code', AUTHORIZATION_CODE)
        const state = url.searchParams.get('state')
        if (state) target.searchParams.set('state', state)
        res.writeHead(302, { location: target.toString() })
        res.end()
        return
      }

      if (req.method === 'POST' && url.pathname === '/oauth2/token') {
        // Accept any (code, verifier) pair — the sandbox never validates
        // PKCE; the app's real flow still sends both (S256).
        const body = new URLSearchParams(await readBody(req))
        if (body.get('grant_type') !== 'authorization_code') {
          res.writeHead(400, { 'content-type': 'application/json' })
          res.end(JSON.stringify({ error: 'unsupported_grant_type' }))
          return
        }
        const tokens = await mintTokens()
        res.writeHead(200, { 'content-type': 'application/json', 'cache-control': 'no-store' })
        res.end(
          JSON.stringify({
            ...tokens,
            refresh_token: REFRESH_TOKEN,
            token_type: 'Bearer',
            expires_in: 3600,
          }),
        )
        return
      }

      res.writeHead(404, { 'content-type': 'application/json' })
      res.end(JSON.stringify({ error: 'not found' }))
    } catch (err) {
      res.writeHead(500, { 'content-type': 'application/json' })
      res.end(JSON.stringify({ error: String(err) }))
    }
  },
)

let closing = false
function shutdown(signal: string): void {
  if (closing) return
  closing = true
  process.stdout.write(`fake-cognito shutting down (${signal})\n`)
  server.closeAllConnections()
  server.close(() => process.exit(0))
  // Never linger past the force-exit window.
  setTimeout(() => process.exit(0), 1500).unref()
}

process.on('SIGTERM', () => shutdown('SIGTERM'))
process.on('SIGINT', () => shutdown('SIGINT'))

server.listen(PORT, HOST, () => {
  process.stdout.write(
    `fake-cognito (sandbox IdP) listening on https://${HOST}:${PORT} (issuer ${ISSUER}, client ${CLIENT_ID}, kid ${KID})\n`,
  )
})
